### ISSUE TITLE
请问Yeelight-pro在hass 自动化里，灯光的色温如何调节？

### ISSUE THREAD

**Issue by ZhiyuZhang** [hasscc/yeelight-pro#14]
您好！ 

我在尝试把灯带加入Hass的自动化。看起来亮度工作都很正常，图形界面下也可以随意调节色温。
但是在自动化里，似乎只能设置亮度，无法设置色温。
鉴于图形界面下可以调节色温，也许是我的参数选择有问题？ 
所以，想请问色温参数是什么，在哪里的文档中能够找到这些参数？
非常感谢！

<img width="538" alt="image" src="https://github.com/hasscc/yeelight-pro/assets/8985935/a1b45ecd-1564-4dcc-949d-28d15e265a85">

**Comment by dengke80622** [comment]
![image](https://github.com/hasscc/yeelight-pro/assets/16779356/06ff284b-c03c-4f50-b177-1e72725e3f1f)

**Comment by al-one** [comment]
```yaml
service: light.turn_on
target:
  entity_id: light.yp3_1747010_light
data:
  kelvin: 5000
```
![image](https://github.com/hasscc/yeelight-pro/assets/4549099/339ba297-d293-4c16-beba-1bb5c56d0e11)
